drop `array_key_exists` for (faster) `isset`
zendframework/zend-expressive-fastroute pull request #61
Opened 2019-02-05 23:41 UTC by pine3ree

...since injected routes are `Route` instances and never `null`

2019-02-06 11:15 UTC, Ocramius requested changes
Since this is an improvement, please target `develop` instead.

2019-02-07 17:04 UTC, geerteltink approved these changes

2019-02-09 15:15 UTC, Ocramius requested changes
Requires a rebase to get rid of commits that were in `master` and not in here

2019-02-09 22:10 UTC, pine3ree commented
@Ocramius rebased (w/o extra merge)

2019-02-09 23:19 UTC, Ocramius commented
Thanks @pine3ree!

2019-02-09 23:19 UTC, merged